browser_name = Chrome

#Dev Environment Details
app_devurl= https://www.kapruka.com/
app_devUserName = ahulshingjamadar@gmail.com
app_devPassword = Skillio@2026

#QA Environment Details
app_qaurl= https://www.kapruka.com/
app_qaUserName = ahulshingjamadar@gmail.com
app_qaPassword = Skillio@2026